sonar.projectKey=leninkart-frontend
sonar.projectName=LeninKart Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx
sonar.exclusions=build/**,coverage/**,node_modules/**
